spring:
    datasource:
        url: jdbc:postgresql://${DATASOURCE-HOST:localhost}:5444/cats-api
        username: admin
        password: admin

    boot:
        admin:
            client:
                url: http://localhost:8080/


management:
    endpoints:
        web:
            exposure:
                include: "*"

server:
    port: 8081