version: '3'
services:
  db-cats-api:
    image: postgres:14.1
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cats-api

